### ISSUE TITLE
Imminent removal from the Google Play Store

### ISSUE THREAD

**Issue by jamie-mh** [stratumauth/app#1162]
On the 3rd of September 2024, my Google Play developer **account will be deleted by Google** and Authenticator Pro will no longer be available on the Google Play store. In line with the new [Play Store policy](https://support.google.com/googleplay/android-developer/answer/14177239), unless I consent to publicly displaying my home address, I will no longer be able to publish apps.

![image](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/4b6ac5ab-2858-4e3a-aa08-f5151cacc20e)

The alternative is to register as an organisation, which involves renting a PO-box and a dedicated support phone number. Of course, this is unreasonable and unsustainable for a free app.

From September, Authenticator Pro will only be available through the F-Droid repos and from GitHub releases.

This is a heads-up for anyone wondering past this date.

**Comment by OmarNazzal150** [comment]
Why is Authenticator Pro is getting removed from the Google Play Store 😢

**Comment by DevynMonroe** [comment]
Dear @jamie-mh,

Oh no! The main reason for this app is to not sell users' info, right? This is because your rating is higher than theirs and they want to intimidate. Like with all the alternative YT apps. It's ridiculous that they have to stomp out anyone who has something better than them. it's not like they don't own everything and that you have to succumb to using their play store. Oh well, we will promote everywhere else. I wouldn't want to be where the owners don't play fair anyways.****_**

Always, 
L.

**Comment by jfsawin** [comment]
Does removal from the Play Store mean that Wear OS compatibility will break or be discontinued? I notice that the website's comparison says it's not supported in the F-Droid version. The Wear OS companion app is the only reason I chose to use Authenticator Pro.

**Comment by MisterDams** [comment]
> Does removal from the Play Store mean that Wear OS compatibility will break or be discontinued?

WearOS app certainly needs to be signed to communicate. That actually is what makes Authenticator so great.

How much would you need for a PO-box ? Maybe we could help with a Donate button.

You could also contact a company or a non-profit organization, in France we have Framasoft that is a huge promoter of open source.

**Comment by jpjonte** [comment]
As @MisterDams said, according to [Play Console help article](https://support.google.com/googleplay/android-developer/answer/13628312?sjid=7251035745412430690-EU) (looks like a EU version of the article), Google Play will only show the country:

> Google will display your legal name, your country (as per your legal address), and developer email address on Google Play. If you decide to monetize on Google Play then Google will display your full address.

I hope this calms your worries, @jamie-mh. If not, I respect your choice!

If you go through with the deletion, what will happen to the Wear OS app?

**Comment by jamie-mh** [comment]
The issue is that I've monetised apps on the account in the past. Despite them being unpublished, the rule applies to all apps, even to those created way before the policy was implemented. I've confirmed this with the Google Play developer support.

Since my account is tainted, the only option is to create a new one and republish the app under a different name. The app won't be removed from anyone's device though.

This sucks because of a few reasons:

- There are [restrictions](https://support.google.com/googleplay/android-developer/answer/14151465?sjid=14571411711282859781-EU) in place for new Google Play accounts - I guess to prevent spam. Not sure how difficult this is to adhere to.
- Users will stop receiving updates and they won't be notified that the app is no longer available. To migrate, they would need to uninstall the old one, install the new one and restore a backup.

I realise that Google Play is the only reasonable way to distribute the Wear OS app. You can sideload APKs but that's not exactly intuitive.

**Comment by jpjonte** [comment]
@jamie-mh I see, that's an unfortunate situation. I'd be fine with sideloading the Wear OS app, but I can see that others might be uncomfortable with that.

**Comment by cheack** [comment]
Did you already published your app to F-Droid? Maybe I missing something, but I'm unable to find it there.

**Comment by fredgolightly** [comment]
Can the git release autoupdate from github or display a notification when there's an update?

**Comment by icantremember** [comment]
Any thoughts on allowing donations for PO box, etc? Hard for me to recommend this app when new users can't install it from the Play Store. 

Thanks for all your work

**Comment by DonnyTheDuck** [comment]
> @jamie-mh Can the git release autoupdate from github or display a notification when there's an update?
You can use Obtanium.
https://github.com/ImranR98/Obtainium

**Comment by Herman-n** [comment]
What is the reason using a separated F-Droid repository instead of the "normal" F-Droid repository?

**Comment by DoctorMcKay** [comment]
I'm dealing with this myself on my own developer account. I believe you should be able to create a new unmonetized developer account and transfer the app to it. I'm happy to sponsor the registration fee for a new dev account if needed.

**Comment by icantremember** [comment]
> > @jamie-mh Can the git release autoupdate from github or display a notification when there's an update?
> > You can use Obtanium.
> > https://github.com/ImranR98/Obtainium

Seconding the recommendation of Obtanium. That's actually how I get and update Authenticator Pro, too.

**Comment by icantremember** [comment]
> I'm dealing with this myself on my own developer account. I believe you should be able to create a new unmonetized developer account and transfer the app to it. I'm happy to sponsor the registration fee for a new dev account if needed.

No idea what the fee is but I'd be willing to contribute as well.

**Comment by bahuma20** [comment]
Did someone already manage to sideload the app to WearOS without play store?

Struggling a little bit here... Is there some tutorial?

**Comment by fredgolightly** [comment]
> That kind of stinks, I was wondering why it was no longer installed on my device. Heads up for anyone that does have it installed via playstore, it may auto uninstall so make sure you have backups.

Wow this is super scary if it auto uninstalls, does this actually happen?

**Comment by jacob153** [comment]
> > That kind of stinks, I was wondering why it was no longer installed on my device. Heads up for anyone that does have it installed via playstore, it may auto uninstall so make sure you have backups.
> 
> I doubt it was removed automatically. From https://support.google.com/googleplay/answer/12246761?hl=en:
> 
> > If an app is removed from Google Play, will the app be removed from my device?
> > No, the app will not be removed from your device. You can continue to use the app, however you will not be able to update your app. If you remove the app from your device, you will not be able to redownload the app unless the developer is able to republish it to Google Play.

I would assume the same. I am only posting my experience which is this morning I could no longer find the app installed on my device. I am the only person that has access to my device. There should be no reason an app should uninstall automatically, but it was clearly not installed on my phone(S24U) anymore and I did not remove it as I depend on it on a daily basis. Maybe I just ran into a bug, or something else has caused this strange behavior, but regardless of if it happened to me it could happen to others.

**Comment by fredgolightly** [comment]
I've imported all my codes from here to 2fas and apart from grid view it's just as good.

**Comment by Lowburn2** [comment]
Thank you @jamie-mh for all your hard work with this app over the years. I used the WearOS app daily since 2022. The fact Google has done this is beyond absurd. I fully support your position. As previously indicated, many of us (myself included) would be happy to sponsor your continued development.

Given that the WearOS app is no longer viable, does anyone know of a worthy alternative? Or, since this app is open source, would it be possible for someone to fork it and republish on the Play Store?  I have tried sideloading it but as mentioned, it can't communicate with the phone app without the Play Store signature.

**Comment by geekthought** [comment]
Please republish with a new account and just add a 15$ price tag. I'll gladly pay again for your app. Sure others will too...

**Comment by nuttylmao** [comment]
WearOS looks like it doesn't work anymore. I sideloaded the APK on my watch and I get the dreaded blue cloud.

**Comment by Lowburn2** [comment]
@nuttylmao  Make sure you're using the correct apks. I just got a new phone and ran into the same issue initially but all is working well now. 

https://github.com/jamie-mh/AuthenticatorPro/releases/tag/1.25.2

You'll want the "me.jmh.authenticatorpro.apk" for your phone and "me.jmh.authenticatorpro.wearos.apk" for your watch.

**Comment by JVKeller** [comment]
> WearOS looks like it doesn't work anymore. I sideloaded the APK on my watch and I get the dreaded blue cloud.

The phone app connection to the wearOS only works with the play store 

![image](https://github.com/user-attachments/assets/9949ecba-bcb5-4f63-94cd-4c21c0acb6d4)

**Comment by nuttylmao** [comment]
> @nuttylmao Make sure you're using the correct apks. I just got a new phone and ran into the same issue initially but all is working well now.
> 
> https://github.com/jamie-mh/AuthenticatorPro/releases/tag/1.25.2
> 
> You'll want the "me.jmh.authenticatorpro.apk" for your phone and "me.jmh.authenticatorpro.wearos.apk" for your watch.

I'm almost positive that's what I did. I'm definitely using that APK for my watch because I just got a new watch today and it was the only way to get it on the watch since it's not on the Play Store anymore.

**Comment by nuttylmao** [comment]
> > WearOS looks like it doesn't work anymore. I sideloaded the APK on my watch and I get the dreaded blue cloud.
> 
> The phone app connection to the wearOS only works with the play store
> 
> ![image](https://private-user-images.githubusercontent.com/29125090/367738766-9949ecba-bcb5-4f63-94cd-4c21c0acb6d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODcyNzcsIm5iZiI6MTcyNjQ4Njk3NywicGF0aCI6Ii8yOTEyNTA5MC8zNjc3Mzg3NjYtOTk0OWVjYmEtYmNiNS00ZjYzLTk0Y2QtNGMyMWMwYWNiNmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDExNDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMjVjMzNmMzExODNkN2YyMDg3YTExNGIwZjU5ZmJhMDMwOTdmZTY1YWE2MTc1MzI0ZjgxYmQ3ZGM5YzQzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36qsewUhIXocSX3eOlygXYlAodlm5bseYbM9Q5SCpQA)

It's not on the Play Store anymore which was my point.

**Comment by JVKeller** [comment]
> > > WearOS looks like it doesn't work anymore. I sideloaded the APK on my watch and I get the dreaded blue cloud.
> > 
> > 
> > The phone app connection to the wearOS only works with the play store
> > ![image](https://private-user-images.githubusercontent.com/29125090/367738766-9949ecba-bcb5-4f63-94cd-4c21c0acb6d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODcyNzcsIm5iZiI6MTcyNjQ4Njk3NywicGF0aCI6Ii8yOTEyNTA5MC8zNjc3Mzg3NjYtOTk0OWVjYmEtYmNiNS00ZjYzLTk0Y2QtNGMyMWMwYWNiNmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDExNDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMjVjMzNmMzExODNkN2YyMDg3YTExNGIwZjU5ZmJhMDMwOTdmZTY1YWE2MTc1MzI0ZjgxYmQ3ZGM5YzQzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36qsewUhIXocSX3eOlygXYlAodlm5bseYbM9Q5SCpQA)
> 
> It's not on the Play Store anymore which was my point.

Yeah, I didn't word it quite right. I fix my comment.

I did have the same issue at first... I installed both and added the tile and saw the no connection cloud. 
BUT! Just now I OPENED THE APP on my watch, rather than just going to the tile, and all is fine. 

Did you launch the app once after you installed it, before you went to the tile?

**Comment by JVKeller** [comment]
> > I'm dealing with this myself on my own developer account. I believe you should be able to create a new unmonetized developer account and transfer the app to it. I'm happy to sponsor the registration fee for a new dev account if needed.
> 
> No idea what the fee is but I'd be willing to contribute as well.

Looks like it's only $25 to register

@jamie-mh, have you decided what you'd like to do yet? We'll get your $25 back and then some! 🤘

**Comment by nuttylmao** [comment]
> > > > WearOS looks like it doesn't work anymore. I sideloaded the APK on my watch and I get the dreaded blue cloud.
> > > 
> > > 
> > > The phone app connection to the wearOS only works with the play store
> > > ![image](https://private-user-images.githubusercontent.com/29125090/367738766-9949ecba-bcb5-4f63-94cd-4c21c0acb6d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODcyNzcsIm5iZiI6MTcyNjQ4Njk3NywicGF0aCI6Ii8yOTEyNTA5MC8zNjc3Mzg3NjYtOTk0OWVjYmEtYmNiNS00ZjYzLTk0Y2QtNGMyMWMwYWNiNmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDExNDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMjVjMzNmMzExODNkN2YyMDg3YTExNGIwZjU5ZmJhMDMwOTdmZTY1YWE2MTc1MzI0ZjgxYmQ3ZGM5YzQzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36qsewUhIXocSX3eOlygXYlAodlm5bseYbM9Q5SCpQA)
> > 
> > 
> > It's not on the Play Store anymore which was my point.
> 
> Yeah, I didn't word it quite right. I fix my comment.
> 
> I did have the same issue at first... I installed both and added the tile and saw the no connection cloud. BUT! Just now I OPENED THE APP on my watch, rather than just going to the tile, and all is fine.
> 
> Did you launch the app once after you installed it, before you went to the tile?

I just installed the APK over the top of my Google Play install. As a last resort, I just uninstalled and reinstalled it and it works now!

**Comment by jamie-mh** [comment]
I have a new developer account now. I'm looking into what it takes to republish.

<img width="621" alt="image" src="https://github.com/user-attachments/assets/665ac7d2-31d2-4cde-9d6f-37373f613eec">

**Comment by smmcdonald** [comment]
Special thank you to @JVKeller and @nuttylmao for the steps to get the WearOS version working. I was about to lose my mind after getting a new smartwatch, as I rarely have my phone on me, but I almost always have my watch.

Here are the steps that worked for me:
1. Create a backup file on the phone app.
2. Download the APKs for the phone and watch here: https://github.com/jamie-mh/AuthenticatorPro/releases/tag/1.25.2
([me.jmh.authenticatorpro.apk](https://github.com/jamie-mh/AuthenticatorPro/releases/download/1.25.2/me.jmh.authenticatorpro.apk) and [me.jmh.authenticatorpro.wearos.apk](https://github.com/jamie-mh/AuthenticatorPro/releases/download/1.25.2/me.jmh.authenticatorpro.wearos.apk) in my case).
Note: it's easier with these steps to download the APK files on the smartphone rather than computer.
3. Uninstall Authenticator Pro on both the phone and smartwatch.
4. Install the primary APK (me.jmh.authenticatorpro.apk) on the phone.
5. Restore the primary app using the backup file in step 1.
6. Install the WearOS APK (me.jmh.authenticatorpro.wearos.apk) via sideload. I used [Wear Installer 2](https://play.google.com/store/apps/details?id=org.freepoc.wearinstaller2). This requires knowledge of using Android wireless debugging.
7. Open the Authenticator Pro app (not the tile) on the smartwatch. At this point the watch app loaded and successfully fetched the OTPs.

@jamie-mh Thank you very much for your work on this application. I want you to know that it is literally life-changing for me, and I'm sure for many others.

**Comment by KlosiakMK** [comment]
> I have a new developer account now. I'm looking into what it takes to republish.
> 

Good to hear. Today I had to reset my WearOS watch and wanted to download again the app but it wasn't there. Started to looking and found this posts thread.
In general Google and its policies stinks. I am happy that you decided to create a new account there. Hope both Android and WearOS apps will be available there soon. Looking forward for that.

Good luck and cheers for the great job that you don with Authenticator Pro app.

**Comment by jamie-mh** [comment]
Hello everyone,

I've published a new version to my new Google Play account, and it's been approved. However, in line with Google's new [app testing requirements](https://support.google.com/googleplay/android-developer/answer/14151465), I must perform a closed test with at least 20 users for 14 days before the app becomes generally available.

For this, I will need your help. If you would like to test the app, the procedure is as follows:

1. Join the testing [Google Group ](https://groups.google.com/u/1/g/stratumauth)
2. Join the test using one of the following links: from Android: https://play.google.com/store/apps/details?id=com.stratumauth.app , from the Web: https://play.google.com/apps/testing/com.stratumauth.app
3. Download the app and test for 14 days

For clarification: the package name is different, so it can be installed alongside the original app. And yes, the name of the app has changed for 2 reasons : (1) because of Google Play's "impersonation" policy and (2) many scam apps have similar names and, I get a lot of emails from people who confuse mine with them, so it's probably for the best.

Cheers

**Comment by JVKeller** [comment]
Links done seem to be working?

**Comment by KlosiakMK** [comment]
@jamie-mh
I can help with testing. Can I import backup from the old app to the new one?

**Comment by hokascha** [comment]
Great, works. Does it already have the wear os companion?

**Comment by DoctorMcKay** [comment]
It's the same app, just with a different name. Backups from the old version import fine and it runs fine on WearOS, since it's the same app.

**Comment by hokascha** [comment]
Play Store didn't offer to install on the WearOS device when trying from my phone. Using the web play store works though.

**Comment by blizbling** [comment]
Hello is there a limitation with the link it's not working on my side i don't know if you have 20 people already

Thank You 
![Capture d’écran 2024-09-25 132627](https://github.com/user-attachments/assets/06220221-7b3e-4645-94ca-08d261ecc6bc)
![Capture d’écran 2024-09-25 132721](https://github.com/user-attachments/assets/7754cb3b-4bc0-40a6-9b54-f4619bf90ef6)

**Comment by jamie-mh** [comment]
> Hello is there a limitation with the link it's not working on my side i don't know if you have 20 people already

Have you joined the Google Group? There is no limit.

**Comment by blizbling** [comment]
my mistake i had click the group didn't join it done thank you verry much of your time, your app help me alot in my day to day work

**Comment by KlosiakMK** [comment]
Joined a group too and installed Stratum app on my phone and WearOS watch. Let the testing begin ;)

**Comment by phbasler** [comment]
Just to be sure: This is the same code as the previous play store deployment?
So except for deployment/setup issues we shouldn't expect to find anything out of the ordinary?

**Comment by jamie-mh** [comment]
> Just to be sure: This is the same code as the previous play store deployment? So except for deployment/setup issues we shouldn't expect to find anything out of the ordinary?

It's built from the [repub](https://github.com/jamie-mh/AuthenticatorPro/tree/repub) branch. Same code base with stuff renamed and a few small tweaks.

**Comment by JVKeller** [comment]
@jamie-mh 

Hey Jamie. So far so good. No issues to report other than you can only install the WearOS version with the Web version of Play. (you probably already knew that by now.)

Ran side by side for a day and now I've removed AP and running just the new app.

Before you start to get flooded with even more messages... Do you plan to migrate to a new Repo? We could start a discussion there to share updates...

**Comment by KlosiakMK** [comment]
Same here...tested today in the morning...codes worked, everything works like on the old app.

**Comment by myrddral** [comment]
Woohoo, I have it up and running again on my phone and my freshly reset GW6 💚 A few hours ago I was quiet desperate about loosing the best feature of this app.

Sooo... is there anything we should do as testers (like feedback, reporting, whatever) or is it just a matter of using the app for at least the given period? @jamie-mh 

Thank you for your work, really appreciate it! I meticulously migrate all my account's security to use 2FA (where applicable), meaning I have to reach for the authenticator at least 4-5 times on a daily basis but at random times. Ever since I've got my watch, I got so used to not having my phone on me all the time... but your app with the wearOS companion makes using 2FA painless :)

**Comment by jamie-mh** [comment]
> Before you start to get flooded with even more messages... Do you plan to migrate to a new Repo? We could start a discussion there to share updates...

Here is fine, I'm not going to change the repo.

> Sooo... is there anything we should do as testers (like feedback, reporting, whatever) or is it just a matter of using the app for at least the given period?

As far as I can tell, the requirement is just to have at least 20 people with the app installed for 14 days. If you have any issues, you can of course report them here.

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/276681ae-77a5-4095-ac97-83ff7f75c9a3">

**Comment by Gravemind2015** [comment]
Joined the group, installed on my Samsung M51. Restored a fresh backup from Authenticator Pro (from Izzy), works perfectly fine so far. Huge thanks for keeping up with google's weird policies :-P.  I'll be keeping it installed and updated until the app gets a full release at least.

I guess the name for the Izzy repo one would be changed as well, to streamline the naming scheme across Izzy and Play? Hopefully that goes smoothly as well.

P.S: I think it might be too late to mention this, considering I can't find the play store entry for Authenticator Pro already but what if a final update was pushed to google play users notifying them (via a dialog popup or something) that the app would be published under a new name and that users needed to manually migrate etc.? I am not aware of the whole procedure about re-publishing so if that required older one to be unpublished first somehow, then probably nothing can be done :-/

**Comment by jamie-mh** [comment]
> P.S: I think it might be too late to mention this, considering I can't find the play store entry for Authenticator Pro already but what if a final update was pushed to google play users notifying them (via a dialog popup or something) that the app would be published under a new name and that users needed to manually migrate etc.? I am not aware of the whole procedure about re-publishing so if that required older one to be unpublished first somehow, then probably nothing can be done :-/

The app is unpublished and I can't push any updates, so there is no way of notifying users. That being said, the app hasn't been uninstalled from devices and will continue to work as-is. It just can't be reinstalled from the Google Play store.

**Comment by Kucharskov** [comment]
I am reading and following this whole thread with bated breath. As soon as I read that I could become a tester I immediately did so! The app works perfectly, and from Google Play I was able to install it on my watch (Galaxy Watch 6) as well. It syncs without a problem, generates correct codes. Wonderfull! 

The only problem I've found is when I return to an open app on the phone from “recently launched” the app closes with a “biometric scan rejected” notification.

P.S What will be the final name of app? I just want to update few places where i wrote about that authenticator ;)

**Comment by ThunderF0x** [comment]
I think it's good that the app is being renamed but the new name “Stratum” should be reconsidered because when I search for “Stratum” in the Google Play Store I find at least 6 apps with this name. In my opinion, a unique name would be better so that there is no risk of confusion. If you search for the name in the Google Play Store, only your app should be found and no other apps.

**Comment by kylemacfarlane** [comment]
I have a bug with the Wear OS app in this version. Do I report it here or a new issue?

If I reopen the app and it already has a previous token selected, the back swipe is very unreliable and I have to swipe 3-6 times to get back to the list to select a different token.

I'm currently using a PW3 with Wear OS 5 and previously I used a PW1 with Wear OS 4. So it could be a Wear OS 5 incompatibility or a new bug in the repub branch.

**Comment by Omnibrain007** [comment]
> I think it's good that the app is being renamed

I think that is really a good idea. Stratum seems to be also a name part of many companies. 
Perhaps you take a new unique name like:  **Jamies Authentificator**

By the way, many thanks for your work!

**Comment by Sominemo** [comment]
A minor thing but I’ll still mention, I like the name starting from "Authenticator" because letter A gets the app listed at the beginning of the app picker on Android and Wear OS.

**Comment by KlosiakMK** [comment]
> A minor thing but I’ll still mention, I like the name starting from "Authenticator" because letter A gets the app listed at the beginning of the app picker on Android and Wear OS.

On the WearOS watch you can move any app on the top of the apps list by longer press of the desired app on the app list, and after that you should be able to move the app to the top of the list. It may be harder to do this on the Android phone I guess.

**Comment by Sominemo** [comment]
> you can move any app on the top of the apps list by longer press of the desired app on the app list, and after that you should be able to move the app to the top of the list

This doesn’t appear to be something I can do on Wear OS 4 Pixel Watch. Long pressing an app opens actions menu.

**Comment by KlosiakMK** [comment]
> > you can move any app on the top of the apps list by longer press of the desired app on the app list, and after that you should be able to move the app to the top of the list
> 
> This doesn’t appear to be something I can do on Wear OS 4 Pixel Watch. Long pressing an app opens actions menu.

I see. It works as described on my TicWatch Pro 5 Enduro with WearOS 4. I thought that it is an app list feature present for all WearOS 4 smartwatches. Looks like I was wrong and it is more likely to be launcher dependent.

**Comment by jamie-mh** [comment]
Hi everyone, thanks for participating in the closed test. I will make the app generally available on Google Play soon.

<img width="451" alt="image" src="https://github.com/user-attachments/assets/f33bc104-e638-48ba-bead-f9e2c9644861">

**Comment by Herman-n** [comment]
I hope there will be enough donations to appreciate the efforts to re-release the app.

I've already given my donation...

**Comment by eltos** [comment]
> I think it's good that the app is being renamed but the new name “Stratum” should be reconsidered because when I search for “Stratum” in the Google Play Store I find at least 6 apps with this name. In my opinion, a unique name would be better so that there is no risk of confusion. If you search for the name in the Google Play Store, only your app should be found and no other apps.

@jamie-mh How about **Authepad**?

Blend word of Authenticator and One-time-pad, so it's self-explaining and representative for the apps purpose. It's truly unique: there are zero results in Google Play, zero results in F-Droid, and even on Google search nothing with this exact name shows up. It's also distinct enough from "Authenticator" to avoid confusion or conflicts. Since the first few letters are equal to the previous app name, the position in alphabetically sorted app lists will be the same, and typing the first letter in your drawers search bar will show it as before, so users for which this is of relevance can keep their habit. Plus it's shorter.

**Comment by Herman-n** [comment]
> 
> @jamie-mh How about **Authepad**?
> 

No.
This app is for OTP = one time password,
not for OTP = one time pad.

Or am I wrong?

**Comment by Kucharskov** [comment]
Anyway guys... @jamie-mh already changed package name, name on GitHub and bought a new domain for that project. I think name was already choosen.

**Comment by KlosiakMK** [comment]
> Anyway guys... @jamie-mh already changed package name, name on GitHub and bought a new domain for that project. I think name was already choosen.

Fully agree. App name were chosen. Steps required for new release in Play Store were done for this app name. I don't see much benefit from renaming the app at this stage. Too much effort with too low outcome.

**Comment by MisterDams** [comment]
I'm glad you figured out a way to keep this app alive!

The new name is a bit lost in my alphabetical app drawer list, might be the right time to add a shortcut on the launcher (should have done it much sooner!)

**Comment by KlosiakMK** [comment]
> @jamie-mh does that mean we should uninstall authenticator pro and install stratumauth? Well, I don't see any reason for you to maintain both authenticator pro and stratumauth (even if they're actually the same), just wanted to be sure.

Authenticator Pro (old app) is no longer supported. It was removed from Google Play Store and there will be no further updates available. It will work on your devices but I would suggest to remove is and switch to the new app version (Stratum). Backups from old one works with the new one by the way.

**Comment by stbxxl** [comment]
The new app (Stratum) seems to be removed from the Google Play Store too. I get a "Not Found" message when I visit [Stratum](https://play.google.com/store/apps/details?id=com.stratumauth.app )

**Comment by rak-rak** [comment]
> The new app (Stratum) seems to be removed from the Google Play Store too. I get a "Not Found" message when I click on the link provided by https://stratumauth.com/download: (https://play.google.com/store/apps/details?id=com.stratumauth.app )

Still available for me. Are you registered fort beta test?

**Comment by AFulgens** [comment]
> The new app (Stratum) seems to be removed from the Google Play Store too. [...]

My 2¢: It's not publicly available yet, "just" for closed/open beta testers, based on the last screenshot from the publishing process posted. We just have to be a bit more patient. I love OSS, when people actually put in the elbow grease. This whole gauntlet with the republishing definitely earned a coffee via the sponsorship link from me 😄 Especially if it works 🤣

**Comment by jamie-mh** [comment]
Hi everyone,

The app has been reviewed by Google and is now publicly available: https://play.google.com/store/apps/details?id=com.stratumauth.app
I'm closing this issue.

**Comment by KlosiakMK** [comment]
Great! Thank you @jamie-mh for all your efforts to make this app available again. Cheers!

**Comment by rak-rak** [comment]
Thank you!

**Comment by Gravemind2015** [comment]
Awesome! I hope it all goes smoothly. Will be looking forward for the name change on the Izzy repo if that's planned.
P.S. It'll be funny to have the encrypted backup file extension still say .authpro :-)

**Comment by IzzySoft** [comment]
@jamie-mh looks like you forgot to drop us a note. And while the changed package name would usually be noticed here, it will take quite a while for that to happen because…

```
$ iod repo get me.jmh.authenticatorpro
me.jmh.authenticatorpro: looking for 'https://api.github.com/repos/stratumauth/app/releases'
me.jmh.authenticatorpro: checking tag 'v1.0.2'
me.jmh.authenticatorpro: lastRelNo set to 'v1.0.2', checking for files
me.jmh.authenticatorpro: Upstream file date (2024-10-18 20:08) is newer than ours (2024-06-25 19:39).
me.jmh.authenticatorpro: returning ['v1.0.2','https://github.com/stratumauth/app/releases/download/v1.0.2/com.stratumauth.app-armeabi-v7a.fdroid.apk',1729274913]
me.jmh.authenticatorpro: 1.25.2 up-to-date.
```

well, `1.0.2 < 1.25.2` :man_shrugging: 

So do you want us to switch to the new package name (guess that's a rhetorical question to be answered by "yes") and, while on it, shall we stick with armeabi (32bit) or switch to arm64?

**Comment by jamie-mh** [comment]
@IzzySoft yep my bad forgot to leave you a mention.

Yes, can you switch to the new package name please. I think we should use the 64-bit build now (it seems like Android has already started phasing out support for 32-bit: #1174). I provide a "fat" apk with all ABIs on my [repo](https://stratumauth.com/fdroid/repo/) for anyone who needs it.

**Comment by IzzySoft** [comment]
Thanks @jamie-mh! I'll then prepare the switch:

* establish the 64bit variant with the new packageName
* add a note to the description of the "old one" pointing it's continued as (link-to) the new one
* set a reminder to remove the "old one" after ~1 month overlap, giving people a chance to see the note and switch
* finally, after ~1 month, removing the "old one".

First 3 bullet points will be completed around 7 pm UTC (with the next sync), so then please change the link behind the IoD badge to `com.stratumauth.app` (just need to adjust the packageName there). All prepared here now:

![image](https://github.com/user-attachments/assets/a629b153-aa69-4914-9395-516a54fd76e3)

> Android has already started phasing out support for 32-bit

No, not Android. Just Google (for their Pixels) and a few other device vendors. Also some chip vendors (e.g. some new ARM chips dropped support, also new SnapDragons) – but some vendors even managed to [re-establish 32bit support](https://phandroid.com/2023/10/31/xiaomi-has-managed-to-get-32-bit-apps-to-run-on-the-snapdragon-8-gen-3/) there.

**Comment by jamie-mh** [comment]
@IzzySoft thanks for changing the package name. I've updated the links in the repo and website to point to the new page.

It still uses the old description though, can it be resynced with the fastlane files in this repo or is it linked to the old page in some way?

**Comment by IzzySoft** [comment]
> I've updated the links in the repo and website to point to the new page.

Thanks!

> It still uses the old description though

My bad, I forgot to manually trigger a Fastlane update. Was notified of this already by an IzzyOnDroid team member, so it was fixed last night – effective with the next sync in about 4h from now.

**Comment by Janeth98-pixel** [comment]
Backup-codes-username
janeliizestrada98@gmail.com.txt
