### ISSUE TITLE
App Crashing on Android 15

### ISSUE THREAD

**Issue by webpixeldesign** [stratumauth/app#1172]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**App Version**
Version number of the app, found in Settings -> About.

**Additional context**

**Comment by jamie-mh** [comment]
It works fine for me (in a emulator at least since Android 15 is not yet released), what does it say exactly?

**Comment by webpixeldesign** [comment]
It was getting stuck on splash screen most of the time, and when it managed to past that sometimes it used to crash. But now it has started working, I didn't even re-install the app. It started working after the tried to open the app in split mode (I was checking Android 15's app pairing feature in split mode)... After which it started working.

**Comment by jamie-mh** [comment]
Doesn't seem to be a problem. Closing this issue.
