### ISSUE TITLE
Removal of monochrome icon

### ISSUE THREAD

**Issue by tmshader** [stratumauth/app#1192]
Not a huge bug, but the monochrome icon was removed from `ic_launcher.xml`, while it was kept in `ic_launcher_round.xml`.

I see that the commit that caused this (d94838f) changed the main icon to vector based, but since the round icon still uses the mipmap monochrome icon, I think it should be kept for the regular icon as well.

**Comment by jamie-mh** [comment]
Fixed in 1.0.1
