### ISSUE TITLE
No available in my country

### ISSUE THREAD

**Issue by Drsheppard01** [stratumauth/app#1209]
I can't use it app from Play Store

But I can download and install app from FDROID

If it's possible please, return possibility for use this app from Play Store with better integration with WearOS

Country: RU

**Comment by skl256** [comment]
![Screenshot_20241106_000510_One UI Home](https://github.com/user-attachments/assets/2e10543b-3d90-467d-9f9f-38a3ab3e428e)
I can confirm this problem :(
